site_name: caretakerd
site_description: caretakerd is a minimal process supervisor build for easy use with no dependencies.
site_author: echocat
repo_url: https://github.com/echocat/caretakerd/
theme_dir: theme
extra_css: [html.css]

extra:
    app:
        daemon: caretakerd
        control: caretakerctl
        hybrid: caretaker

pages:
- "Home": index.md
- "Configuration":
    - "Examples": "configuration/examples.md"
    - "Data Types":
        - "Caretakerd": "configuration/datatypes/Caretakerd.md"
        - "LoggerLevel": "configuration/datatypes/LoggerLevel.md"
        - "Logger": "configuration/datatypes/Logger.md"
        - "Rpc": "configuration/datatypes/Rpc.md"
        - "Security": "configuration/datatypes/Security.md"
        - "SecurityType": "configuration/datatypes/SecurityType.md"

        - "Boolean": "configuration/datatypes/Boolean.md"
        - "Integer": "configuration/datatypes/Integer.md"
        - "NonNegativeInteger": "configuration/datatypes/NonNegativeInteger.md"
        - "SocketAddress": "configuration/datatypes/SocketAddress.md"
        - "String": "configuration/datatypes/String.md"

theme: readthedocs
strict: true
use_directory_urls: true

markdown_extensions:
    - attr_list
    - toc:
        permalink: False
    - admonition
